### PR TITLE
License updates.

### PR DESCRIPTION
**Pull request by pq**
@seaneagan @sethladd

### CODE REVIEW

**Comment by sethladd** [comment]
lgtm

**Comment by seaneagan** [comment]
Do we need both AUTHORS and pubspec.yaml authors?  quiver removed AUTHORS when I asked the same question:

**Comment by seaneagan** [comment]
https://github.com/google/quiver-dart/issues/253

**Comment by pq** [comment]
> Do we need both AUTHORS and pubspec.yaml authors?

Good question.  My sense that this is important for IP reasons.  It's redundant for sure but better safe than sorry?  @sethladd ?

**Comment by sethladd** [comment]
Keep AUTHORS for now.

**Comment by pq** [comment]
:+1: 

Otherwise reasonable @seaneagan?

**Comment by seaneagan** [comment]
lgtm

**Pull request merged**
